<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2013-04-27 12:48

$extensionPath = t3lib_extMgm::extPath('datahandler_test');
return array(
	'tx_datahandlertest_regularworkspacestest' => $extensionPath . 'Tests/Unit/RegularWorkspacesTest.php',
	'tx_datahandlertest_service_simulationservice' => $extensionPath . 'Service/SimulationService.php',
	'tx_datahandlertest_structure_element' => $extensionPath . 'Structure/Element.php',
	'tx_datahandlertest_unit_abstract' => $extensionPath . 'Tests/Unit/Abstract.php',
	'tx_datahandlertest_unit_abstractlocalization' => $extensionPath . 'Tests/Unit/AbstractLocalization.php',
	'tx_datahandlertest_unit_abstractworkspaces' => $extensionPath . 'Tests/Unit/AbstractWorkspaces.php',
);
?>